### ISSUE TITLE
Custom recipe support for CompactMachines3

### ISSUE THREAD

**Issue by winterSteve25** [userTravis/Chambers#2]
Give more slots to the compact chambers please. Some custom recipes i made have more than 4 components

**Comment by userTravis** [comment]
I will not be able to support custom recipes for the miniaturization field, this is due to how the recipes are made in the 3 dimensional space. Crafting in world allows for recipes that call for the same input ingredients in multiple recipes. 
Take for example:
- Tiny Compact Macine (Raw materials: 26 Compact Machine Walls, 1 Ender Pearl)
- Large Compact Machine (Raw materials: 98 Compact Machine Walls, 1 Ender Pearl)

If I added a block to craft all these recipes then if you try to craft the Large, as soon as enough materials are in for the Tiny, the machine would start crafting the Tiny right away.

I am of course open to other options, currently I am just out of ideas for how this could work. That is why the current implementation is 2 separate machines with "hard-coded" recipes.

(note: the Woot Anvil Chambers are a unique case because the only recipe that had to be moved to a separate machine was the Soul Dust, this was easy enough to simply blacklist that one single recipe and then whitelist it on a separate machine. That design allowed me to support CraftTweaker/custom recipes for the anvil. It unfortunately does not work for Compact Machines recipes where a lot of recipes rely on the same input ingredients)

**Comment by userTravis** [comment]
Anyone who is able to provide me with ideas or a way for how this could work, I would love that. I have no problem with implementing this, I just am out of ideas myself for how this could be possible.

**Comment by winterSteve25** [comment]
Oh, i see the problem here now. I'm a pack dev, barely know anything about modding. But is this possible:
Try add a button in the gui or make it only start crafting with a redstone signal.

Just something that could work. But I don't know if its possible to do in the mod.

**Comment by userTravis** [comment]
That could possibly work but...
It will depend on the order of the recipes stored in the actual CompactMachines3 mod code(which seems to be random every time you start MC and even if the actual mods recipes was not, I do not have a way to know which custom recipes will be loaded first in custom packs), as the recipe-matcher finds the first matching recipe and returns that to my mod. Also while there are some fancy methods(that are not as performance friendly) I can think of to "force" it to perform the recipe with the most amount of input ingredients, then the following situation/issue will arise:
- what if the recipe with the most ingredients is not what the player is trying to craft? Take for example using AE2 to craft 10 Tiny Compact Machines, the network will input 260(or as many as can fit) Compact Machine Walls into the Chamber. This would still cause the Chamber to end up crafting Large Compact Machines as the AE2 network spits out as many materials as it can into a machine.

Some other issues I thought of when pondering the "redstone activated" style machine:
1. When players automate these kind of machines they usually do so by placing a redstone clock/timer directly adjacent to the machine in an effort to get it to attempt crafting all the time. For example look up what some clever people do to "automate" Draconic Fusion Crafting. Not to mention AE2 does not support a "redstone pulse only after all input ingredients are inserted into a machine" mode.
2. Still the issue of which recipe to craft will persist if attempting to automate this machine. As the end goal of this mod is to allow easier automation for complex multi-blocks/in world crafting, forcing the player to work with redstone timers feels like deviation from that goal.

I do like the brainstorming though, so far the only possible solution I see would be a Chamber that only crafts the recipe of the currently selected item(ghost item style), however the issue with this implementation would be that the player would need 1 Chamber for each and every recipe they wish to have automated, and with some mod-packs adding a lot of recipes it would quickly get out of hand. Do remember another goal of the mod is less tile-entity's.

**Comment by userTravis** [comment]
Basically the issue is the Chamber would not know which recipe to select for crafting, and the redstone signal/button press would make automation of the Chamber about as impossible as the actual mods in-world-crafting anyway which seems to defeat the purpose of this mod in the first place.

**Comment by userTravis** [comment]
One last issue I can see is that some mod-packs have VERY complicated recipes for CompactMachines3, and with a 9x9x9(not even the biggest) cube that would be 729 input slots. The issue is how many slots should the machine support? Some players screens are not even big enough to display that many slots in a given GUI. Supporting custom recipes would then have to mean not supporting the very complicated recipes simply because there would be too many input types and not enough slots in the GUI.

**Comment by winterSteve25** [comment]
Like the problem about automation I think is what players need to worry about not mod devs. Of course you can make the mod machines easy to automate. But mods like ember (exchange table crafting), and like you said draconic evolution infusion. Its not meant to be automated. But players figure ways out to automate it. (I do understand a reason "chamber" this mod exist is for player easier to automate stuff like compact machine). Also just an idea about recipe conflicts, you can do something like alchemistry, use JEI to lock up a recipe in the machine. Or (idk if its possible) to make like a built in nomorerecipeconflict mod for the chamber

**Comment by userTravis** [comment]
The source for CompactMachines3 is on GitHub [here is where the Recipe Integration is found](https://github.com/CompactMods/CompactMachines/tree/1.12.1/src/main/java/org/dave/compactmachines3/miniaturization), the issue is just that I can not think of a way to integrate with this. The code for my "Field Projector Chamber" is my only block that uses hard coded recipes, as such I am not proud to share it. I intended to clean it up with a more logical clean design that supports custom recipes but I have not been able to think of any ways to do so.

As you can see CM3 code actually verifies the 3D structure is assembled in the world, the way of checking is resource intensive enough to not be able to be done regularly such as every tick. The CM3 mod checks only when the catalyst ingredient is detected inside the 3D space as a thrown entity. Although I see ways I could grab the "recipes" from their mod, their mod relies on the order in the XYZ space to match what is programmed in each recipe. I can't reasonably see a way to turn this into a GUI setup, especially not without serious resource usage every time it checks for a matching recipe. As the purpose of my mod is to _reduce_ lag I decided against the ideas I had such as "brute forcing" the recipe checker.

**Comment by MechOrigin** [comment]
Hey userTravis, SecretAsain here from curseforge.

I gave it some thought and the only way I can see this being implemented with very little edge case issues like the ones this thread has listed is this.

I have seen in the resourceloader function inside multiblockrecipes.java that it checks for recipes. Now you can have big or small recipes 13x13x13 or 1x1x1. As well as recipes with the exactly same amount of materials, even in the same configuration except with a different catalyst. Game will crash if you try and load two similar recipes. As you cannot have the same materials configured the same way with the same catalyst without conflicting, 
The second problem is stack size and for recipes such as 13x13x13 could be around 1000 blocks HOLLOW and 2000 blocks SOLID.
Anyways my conclusion is this can be solved with a few different methods.

The first solution is to implement a larger stack limit inside the storage "memory" of that block. For example if a recipe calls for 256 iron bars. It will take 4 stacks of iron bars and hold that in memory as 256 (perhaps NBT data) iron bars in a single slot. There are other mods that do this sort of block transformation into an integer of that nbt similar to the mod dank/null. I believe it's open source could help give some ideas on how to do this. This is so that recipes calling for like 300 blocks of several materials can be indexed and then used up.

Secondly, is to check for added recipes from the multiblockrecipes.java it does a resourcesloader. Then the important thing to do is to Compare the recipe added by the json to the materials and catalyst given (per compactmachines given ticks as to not heavily impact resources) Therefore bypassing the need for 3d space checking. 

The solution is to implement the max blocks allowed by compact machines in a given recipe to your chamber as well. I think I see in JEI that it shows like 6 or something slots? Which should hold up to maybe the max value of a short integer? 32767 .... I mean 3000 should suffice too lol... and 1 catalyst, which is checked by resourceloader and compared to the recipe in the json..... and 1 output. do the same with these implementations and huzzah.

https://i.imgur.com/LFBDg8q.jpg

**Comment by userTravis** [comment]
Hmm I never thought about limiting the Chamber to only work with recipes that have 6 or less input ingredients. 
Does the CM3 mod natively support recipes with more then 6(without glitching the JEI GUI?)? I am wondering if its common enough to stress over not supporting those advanced recipes with more then 6, as if I am to implement this I want to do it with full support as best as possible as to not have to explain to people how it works, would want it mostly self explanatory.

Also can you tell me which pack your playing on? Would like to see some examples of custom recipes.

As far as the "65+ stack sizes" goes, I have never been a real fan of the way it works, it always has lots of issues and trouble interacting with other mods/machines. Even /dank/null and other popular well developed ones, Minecraft just wasn't built for that kind of thing. The highly advanced/technical way that powerful mods like AE/RS do it is far beyond the scope of my mod(and what I am capable of). Thankfully even 2,000 blocks is only around 30 stacks or 3x10 inventory slots, so I don't see that being a big deal.

How about a GUI similar to a small chest, and an input(ghost style) for what is trying to be made, if the "chest" slots contain the ingredients the recipe can begin processing?(or even 9 ghost style input slots as to minimize how many auto crafting interfaces are needed. I wish there was a more _elegant_ method.

**Comment by MechOrigin** [comment]
Yeah I dont think CM3 mod supports more than 6 items. You could try it out but it crashes for me trying to even load a recipe bigger than 6 inputs types.

Yeah it's my modpack: Not Too Complicated. Check it out. https://www.curseforge.com/minecraft/modpacks/not-too-complicated
Here's a video too.
https://i.imgur.com/BhCjNcI.mp4

Okay fair enough. The 2000 blocks is doable though.

Yeah that's a good idea, if there is a way to make a (ghost) style inputs. That's right on the money with what I was thinking.
It's tough to turn a 3d space into a 2d space without gainign some grey hairs lol

An output (ghost) item is also an alternative, where it's inventory is then processed based on the output desired but that breaks the automation of multiple recipe types if desired.

**Comment by userTravis** [comment]
Good to know that CM3 will forcibly reject recipes of 7+ inputs, that means this should be **far** simpler then I originally intended.

Right now I am considering doing something like how the "Deep Storage Unit" works(max 8192 storage instead of INT_MAX) to store each of the 6 input items.

Now I just have to figure out why none of CM3 default recipes load in my test environment...

EDIT: After looking into CM3 config, I see a setting:

    # Maximum size the field projectors can cover [range: 5 ~ 20, default: 15]
    I:maximumCraftingAreaSize=15
This means the Chamber must be capable of storing 8,192 items of each input.

**Comment by MechOrigin** [comment]
Yeah I didn't see that config, interesting. Which means a max is 20x20x20, thank the lord I've never played a pack with that kind of build lol...

That's a great idea to use Deep Storage Unit type mechanics. Using 8192 as max instead of intmax will work nicely.

Did you end up figuring out why your CM3 default recipes didnt load?

**Comment by userTravis** [comment]
Hah yeah same, and no however I got the custom recipes loaded which may even work better as I can manually check for any edge cases.

**Comment by MechOrigin** [comment]
Great news, I'm excited to test what you've come up with in the next release :)

**Comment by userTravis** [comment]
Do the custom recipes support matching NBT on any of the 6 input types?

I know the catalyst item does like this(from CM3 curseforge page):
`"catalyst-nbt": "{StoredEnchantments: [{lvl:3s,id: 11s}]}",`

Also I know the target item does like this(from your modpacks "capsule_3x3.JSON"):
`"target-nbt": "{color: 13421772, size: 3}",`

None of your custom recipes request a specific NBT on the input types, nor am I aware of any modpack that does.
(I know meta is confirmed for all 3)

EDIT
[Line 183](https://github.com/CompactMods/CompactMachines/blob/1.12.1/src/main/java/org/dave/compactmachines3/miniaturization/MultiblockRecipeSerializer.java) appears to show "input-nbt" would be how to use it, but I am not too familiar with custom NBT, I just know skipping it would be bad, take the following examples:
- Energy Storage Block with 1 billion "energy" stored as NBT being used as an input type.
- Crazy modpacks that try to do something like a Shulker box containing other late/end-game items as an input type.

If you are able to make a recipe that requires special NBT on the input types could you share it with me?

**Comment by MechOrigin** [comment]
Yes it does allow things like that. I've experimented before with using the mekanism cells stored with like whatever max it was.. 200million or something?
`<mekanism:energycube>.withTag({tier: 3, mekData: {energyStored: 1.28E8}})` but the catalyst equivalent json....

Anyways there is a seprate line for input-nbt 

and its weird... I have an example of it I think in my code... i forget where? maybe i removed it idk...

But it's similar to this:
```"input-nbt": {
"a:A": { "nbt": "{\"cm3_extra:ThermalDynamicsGrid\":{Connections:[2,0,0,2,0,2]},id:\"thermaldynamics:duct_energy_basic\"}" },
"a:B": { "nbt": "{\"cm3_extra:ThermalDynamicsGrid\":{Connections:[0,0,2,2,0,0]},id:\"thermaldynamics:duct_energy_basic\"}" },
"a:C": { "nbt": "{\"cm3_extra:ThermalDynamicsGrid\":{Connections:[2,0,2,0,0,2]},id:\"thermaldynamics:duct_energy_basic\"}" },
"a:D": { "nbt": "{\"cm3_extra:ThermalDynamicsGrid\":{Connections:[2,2,0,0,0,0]},id:\"thermaldynamics:duct_energy_basic\"}" },
"a:E": { "nbt": "{\"cm3_extra:ThermalDynamicsGrid\":{Connections:[0,2,0,2,0,2]},id:\"thermaldynamics:duct_energy_basic\"}" },
"a:F": { "nbt": "{\"cm3_extra:ThermalDynamicsGrid\":{Connections:[0,2,2,0,0,2]},id:\"thermaldynamics:duct_energy_basic\"}" },
"a:G": { "nbt": "{\"cm3_extra:ThermalDynamicsGrid\":{Connections:[0,0,0,0,2,2]},id:\"thermaldynamics:duct_energy_basic\"}" },
"b:A": { "nbt": "{Items:[],id:\"minecraft:chest\",Lock:\"\"}" },
"a:H": { "nbt": "{\"cm3_extra:ThermalDynamicsGrid\":{Connections:[2,0,0,2,2,0]},id:\"thermaldynamics:duct_energy_basic\"}" },
"a:I": { "nbt": "{\"cm3_extra:ThermalDynamicsGrid\":{Connections:[2,0,2,0,2,0]},id:\"thermaldynamics:duct_energy_basic\"}" },
"a:J": { "nbt": "{\"cm3_extra:ThermalDynamicsGrid\":{Connections:[0,2,0,2,2,0]},id:\"thermaldynamics:duct_energy_basic\"}" },
"a:K": { "nbt": "{\"cm3_extra:ThermalDynamicsGrid\":{Connections:[0,2,2,0,2,0]},id:\"thermaldynamics:duct_energy_basic\"}" }
}
```
notice that the original letter of the 3d block is appended with a upper case letter as the nbt data. This is very different than the upper case default recipes I use to declare inputs

**Comment by MechOrigin** [comment]
```
{
  "name": "compactmachines3:energy_cell", "disabled": true,
  "target-item": "thermalexpansion:cell", "target-count": 1,
  "duration": 300,
  "symmetrical": true,
  "catalyst": "minecraft:blaze_powder",
  "input-types": { "a": { "id": "thermaldynamics:duct_0", "meta": 0 }, "b": { "id": "minecraft:chest", "meta": 0, "ignore-meta": true } },
  "input-nbt": {
    "a:A": { "nbt": "{\"cm3_extra:ThermalDynamicsGrid\":{Connections:[2,0,0,2,0,2]},Energy:{},id:\"thermaldynamics:duct_energy_basic\",Attachments:[]}" },
    "a:B": { "nbt": "{\"cm3_extra:ThermalDynamicsGrid\":{Connections:[0,0,2,2,0,0]},Energy:{},id:\"thermaldynamics:duct_energy_basic\",Attachments:[]}" },
    "a:C": { "nbt": "{\"cm3_extra:ThermalDynamicsGrid\":{Connections:[2,0,2,0,0,2]},Energy:{},id:\"thermaldynamics:duct_energy_basic\",Attachments:[]}" },
    "a:D": { "nbt": "{\"cm3_extra:ThermalDynamicsGrid\":{Connections:[2,2,0,0,0,0]},Energy:{},id:\"thermaldynamics:duct_energy_basic\",Attachments:[]}" },
    "a:E": { "nbt": "{\"cm3_extra:ThermalDynamicsGrid\":{Connections:[0,2,0,2,0,2]},Energy:{},id:\"thermaldynamics:duct_energy_basic\",Attachments:[]}" },
    "a:F": { "nbt": "{\"cm3_extra:ThermalDynamicsGrid\":{Connections:[0,2,2,0,0,2]},Energy:{},id:\"thermaldynamics:duct_energy_basic\",Attachments:[]}" },
    "a:G": { "nbt": "{\"cm3_extra:ThermalDynamicsGrid\":{Connections:[0,0,0,0,2,2]},Energy:{},id:\"thermaldynamics:duct_energy_basic\",Attachments:[]}" },
    "b:A": { "nbt": "{Items:[],id:\"minecraft:chest\",Lock:\"\"}" },
    "a:H": { "nbt": "{\"cm3_extra:ThermalDynamicsGrid\":{Connections:[2,0,0,2,2,0]},Energy:{},id:\"thermaldynamics:duct_energy_basic\",Attachments:[]}" },
    "a:I": { "nbt": "{\"cm3_extra:ThermalDynamicsGrid\":{Connections:[2,0,2,0,2,0]},Energy:{},id:\"thermaldynamics:duct_energy_basic\",Attachments:[]}" },
    "a:J": { "nbt": "{\"cm3_extra:ThermalDynamicsGrid\":{Connections:[0,2,0,2,2,0]},Energy:{},id:\"thermaldynamics:duct_energy_basic\",Attachments:[]}" },
    "a:K": { "nbt": "{\"cm3_extra:ThermalDynamicsGrid\":{Connections:[0,2,2,0,2,0]},Energy:{},id:\"thermaldynamics:duct_energy_basic\",Attachments:[]}" }
  },
  "shape": [
    [ [ "a:A", "a:G", "a:H" ], [ "a:B", "_", "a:B" ], [ "a:C", "a:G", "a:I" ] ],
    [ [ "a:D", "_", "a:D" ], [ "_", "b:A", "_" ], [ "a:D", "_", "a:D" ] ],
    [ [ "a:E", "a:G", "a:J" ], [ "a:B", "_", "a:B" ], [ "a:F", "a:G", "a:K" ] ]
  ]
}
```

here's an example page of where this came from:

https://ftb.gamepedia.com/Default_Compact_Machines_Recipe_Archive

**Comment by userTravis** [comment]
Hmm this may be problematic as the [getRequiredItemStacks()](https://github.com/CompactMods/CompactMachines/blob/6c1a60f4108fb9eb16b94ec034108c0481c0e292/src/main/java/org/dave/compactmachines3/miniaturization/MultiblockRecipe.java#L103) function does not appear to provide me with anyway of obtaining the NBT requirements specified in the custom recipes. As there is not a "true" API for CM3 to provide other mods a list of recipes, I had to resort to using the function that is for JEI recipe viewing which seems to omit NBT on input items?

**Comment by MechOrigin** [comment]
Hm interesting... idk what about in [MultiblockRecipeSerializer()](https://github.com/CompactMods/CompactMachines/blob/6c1a60f4108fb9eb16b94ec034108c0481c0e292/src/main/java/org/dave/compactmachines3/miniaturization/MultiblockRecipeSerializer.java) under ```if(jsonRoot.has("target-nbt")) {}``` function? Is there any way to capture that NBT data the way this does? Similarly for `input-nbt` as well

```// Read variant map
        if(jsonRoot.has("input-nbt")) {}
```
Basically let CM3 do all the work and just read what's there.

**Comment by userTravis** [comment]
That appears to be called as the CM3 mod initially loads in all the **custom** recipes for the first time, pulling them into its own registries(It does not have any public methods/functions I could call to get the recipes into my mod). The NBT is stored only in private variables in CM3 code after it is read.

What about having Chambers directly read the JSON files(similarly to what happens in that file)?

The only problem I see with this approach is I'm not sure how that would work with the default recipes as the default recipes are not housed in JSON files, and I don't see where they get loaded in. Are the default recipes hard-coded and always on? I don't want to force them always on if some mod packs turn them off.

**Comment by MechOrigin** [comment]
I believe the default recipes are hard coded, always on and unchangeable (except by the mod author), but can be overridden if the name of the json is inside config/CM3/recipes directory. So if I want to change a default machine frame for example `machine-normal.json` and change out a gold block with a block of mushroom I can if I want too.

That's a shame, it's really tough not having a "real" api...

**Comment by userTravis** [comment]
Yeah I am really starting to think this may be more work then it's worth. It's one thing to work with custom recipe registries like how pulverizes/macerators function utilizing forge to easily add there own recipe registries, but completely different to attempt to integrate with a fully custom designed system.

Reading the files manually would involve me copying a large amount of code directly from CM3 source which I do not feel comfortable doing out of respect for the mod author(CM3 recipe JSONs can be very complex, as such so is the code that reads them).

At this point the only option left may be to submit a GitHub issue to CM3, but I tend to avoid doing that myself as I've heard mod developers tend to not like me because my mod can be seen as a way that functions as a work-around to the complex systems they worked hard on designing. Also after browsing the CM3 GitHub I see they're already finalizing the last 1.12.2 release and are working on 1.16 as of now.

As I have no plans to push Chambers to newer versions as most of my supported mods are still on 1.12.2, I do not believe this feature will ever be implemented.

**Comment by userTravis** [comment]
Adding to my previous comment, even with permission/support from CM3 to do this, it still would not be possible without high risk of horribly breaking custom recipes. Take [example.zombieegg.json](https://ftb.gamepedia.com/Default_Compact_Machines_Recipe_Archive) my code would have to somehow "know" which input to use, the actual in-world block(fire in this case) or the item used to create the block(flint and steel in this case).

If my code selected the blocks instead of the items that show in CM3 JEI then there is risk that players cannot obtain said blocks(fire for this example is unobtainable in mc 1.12.2). On the other hand if I opt to use the items in recipes, players may get confused and not know how to craft a recipe that shows something like fire as an input in CM3 JEI, or worse, unobtainable NBT such as "Furnace with items smelting" as an input, "fully charged ME controller"(energy is lost on block break, impossible to obtain) or "chest full of diamonds" not needing diamonds, thus breaking progression on difficult packs.

There is unfortunately far too many "what ifs" that would arise from adding support for custom CM3 recipes.

**Comment by MechOrigin** [comment]
fair enough. This is too bad :(

Thank you for trying anyways and your hard work.
